config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  resources :places do
    resources :forecasts, only: [:show, :create, :edit]
  end
  resources :forecasts, only: [:index, :new, :update, :destroy]
  root 'weather#index'

  mount Sidekiq::Web, at: '/sidekiq'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forecast.rb
class Forecast < ApplicationRecord
  belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :forecasts
  geocoded_by :address
  after_validation :geocode if :address_changed?

  reverse_geocoded_by :latitude, :longitude do |obj,results|
    if geo = results.first
      obj.zipcode = geo.postal_code
      obj.city = geo.city
      obj.state = geo.state_code
    end
  end

  after_validation :reverse_geocode if :address_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  before_action :set_forecast, only: %i[ show edit update destroy ]

  # GET /forecasts or /forecasts.json
  def index
    @forecasts = Forecast.all
  end

  # GET /forecasts/1 or /forecasts/1.json
  def show
  end

  # GET /forecasts/new
  def new
    @forecast = Forecast.new
  end

  # GET /forecasts/1/edit
  def edit
  end

  # POST /forecasts or /forecasts.json
  def create
    @forecast = Forecast.new(forecast_params)

    respond_to do |format|
      if @forecast.save
        format.html { redirect_to forecast_url(@forecast), notice: "Forecast was successfully created." }
        format.json { render :show, status: :created, location: @forecast }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forecasts/1 or /forecasts/1.json
  def update
    respond_to do |format|
      if @forecast.update(forecast_params)
        format.html { redirect_to forecast_url(@forecast), notice: "Forecast was successfully updated." }
        format.json { render :show, status: :ok, location: @forecast }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forecasts/1 or /forecasts/1.json
  def destroy
    @forecast.destroy

    respond_to do |format|
      format.html { redirect_to forecasts_url, notice: "Forecast was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forecast
      @forecast = Forecast.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def forecast_params
      params.require(:forecast).permit(:current_temp, :high_temp, :low_temp, :zipcode, :place_id)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show edit update destroy ]

  # GET /places or /places.json
  def index
    @places = Place.all
  end

  # GET /places/1 or /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        forecast, cache_hit = check_cache_call_services
        # QueryForecastServicesJob.perform_later(@place.id)
        format.html { redirect_to place_forecast_path(forecast.place_id, forecast.id, cache_hit: cache_hit), notice: "Location found." }
        # format.html { redirect_to place_url(@place), notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to place_url(@place), notice: "Place was successfully updated." }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1 or /places/1.json
  def destroy
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url, notice: "Place was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def check_cache_call_services
      #set cache key and check if it already exist
      cache_key = "#{@place.zipcode}"
      cache_hit = Rails.cache.exist?(cache_key)
      forecast = Rails.cache.fetch(cache_key, expires_in: 30.minutes) do
        open_weather = OpenWeatherAPI.new(@place.latitude, @place.longitude).call
        gov_weather = WeatherDotGovAPI.new(@place.latitude, @place.longitude).call
        Forecast.create(high_temp: open_weather&.high_temp,
                        low_temp: open_weather&.low_temp,
                        current_temp: open_weather&.temp,
                        icon: open_weather&.icon,
                        place_id: @place&.id,
                        zipcode: @place&.zipcode,
                        details: gov_weather&.details,
                        wind_direction: gov_weather&.wind_direction,
                        wind_speed: gov_weather&.wind_speed
                        )
      end
      return forecast, cache_hit
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name, :zipcode, :latitude, :longitude, :address)
    end
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/forecasts/_form.html.erb
<%= form_with(model: forecast) do |form| %>
  <% if forecast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forecast.errors.count, "error") %> prohibited this forecast from being saved:</h2>

      <ul>
        <% forecast.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :current_temp %>
    <%= form.text_field :current_temp %>
  </div>

  <div class="field">
    <%= form.label :high_temp %>
    <%= form.text_field :high_temp %>
  </div>

  <div class="field">
    <%= form.label :low_temp %>
    <%= form.text_field :low_temp %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode %>
  </div>

  <div class="field">
    <%= form.label :place_id %>
    <%= form.text_field :place_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/forecasts/edit.html.erb
<h1>Editing Forecast</h1>

<%= render 'form', forecast: @forecast %>

<%= link_to 'Show', @forecast %> |
<%= link_to 'Back', forecasts_path %>

app/views/forecasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forecasts</h1>

<table>
  <thead>
    <tr>
      <th>Current temp</th>
      <th>High temp</th>
      <th>Low temp</th>
      <th>Zipcode</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forecasts.each do |forecast| %>
      <tr>
        <td><%= forecast.current_temp %></td>
        <td><%= forecast.high_temp %></td>
        <td><%= forecast.low_temp %></td>
        <td><%= forecast.zipcode %></td>
        <td><%= forecast.place_id %></td>
        <td><%= link_to 'Show', place_forecast_path(forecast.place_id, id: forecast.id) %></td>
        <td><%= link_to 'Edit', edit_place_forecast_path(forecast.place.id, id: forecast.id) %></td>
        <td><%= link_to 'Destroy', forecast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forecast', new_forecast_path %>

app/views/forecasts/new.html.erb
<h1>New Forecast</h1>

<%= render 'form', forecast: @forecast %>

<%= link_to 'Back', forecasts_path %>

app/views/forecasts/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h3>Weather forecast for <%= "#{@forecast.place.city}, #{@forecast.place.state}" %></h3>
  <h5>Zipcode: <%= @forecast.zipcode %></h5>

  <h6 style="width: 500px; height: auto;"><%= @forecast.details %></h6>
  <br />

  <p>
    <strong>Current temp:</strong>
    <%= @forecast.current_temp %>
  </p>

  <% unless @forecast.feels_like.blank? %>
  <p>
    <strong>Feels like:</strong>
    <%= @forecast.feels_like %>
  </p>
  <% end %>

  <p>
    <strong>High temp:</strong>
    <%= @forecast.high_temp %>
  </p>

  <p>
    <strong>Low temp:</strong>
    <%= @forecast.low_temp %>
  </p>
  <% if params[:cache_hit] %>
    <p>
      <strong>cache hit:</strong>
      <%= params[:cache_hit] %>
    </p>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <%= link_to "Home", root_path, class: 'link-secondary h1', data: { turbolinks: false } %>
    <br />
    <%= link_to "Places", places_path, class: 'link-secondary h4' %>
    <br />
    <%= link_to "Forecasts", forecasts_path, class: 'link-secondary h4' %>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV.fetch('GOOGLE_PLACE_API') %>&libraries=places&callback=initMap" async defer data-turbolinks-eval="false"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with(model: place) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
        <% place.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>State</th>
      <th>Zipcode</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.city %></td>
        <td><%= place.state %></td>
        <td><%= place.zipcode %></td>
        <td><%= place.latitude %></td>
        <td><%= place.longitude %></td>
        <td><%= place.address %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @place.zipcode %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/weather/index.html.erb
 <%= javascript_pack_tag 'initMap' %>
<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Address Search</h1>
        <p class="lead text-muted">find out weather below</p>
        <%= form_for :place, url: places_path  do |f| %>
          <div class='input-group'>
            <%= f.text_field :address, id:'address', class: 'form-control form-control-lg' %>
            <%= f.submit 'Search', class: 'btn btn-outline-secondary' %>
          </div>
        <% end %>

        <div class='forecast'> </div>
      </div>
    </div>
  </section>
</main>